"""compile_excel 命令行拒绝 cex_author_emit 出件的 cases.json（评审：「改 cases.json 再编译」让脑图批
绕过引擎的全部提交规则闸）；cex_author_emit 自己的出件路径不受影响。"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPTS = REPO_ROOT / "skills" / "compile-excel" / "scripts"

pytest.importorskip("openpyxl")

EMITTED = {"batch": "emitted_b", "_generated": "generated by cex_author_emit from sealed mechanical cases",
           "cases": [{"autoid": "202609270000000001", "priority": "P1", "steps": [
               {"E": "APV_0", "F": "cmd_config", "G": "show version", "desc": "观察"},
               {"E": "check_point", "F": "found", "G": "Version:", "desc": "断言",
                "source": {"kind": "intent", "ref": "u1:202609270000000001:1:1"}}]}]}


def _compile(tmp_path: Path, *extra: str) -> subprocess.CompletedProcess:
    cases = tmp_path / "cases.json"
    cases.write_text(json.dumps(EMITTED, ensure_ascii=False), encoding="utf-8")
    return subprocess.run([sys.executable, str(SCRIPTS / "compile_excel.py"), "--cases", str(cases),
                           "--out", str(tmp_path / "out"), *extra],
                          capture_output=True, text=True, timeout=120, check=False)


def test_cli_refuses_an_emitted_cases_json(tmp_path):
    proc = _compile(tmp_path)
    assert proc.returncode == 1
    error = json.loads(proc.stdout)["error"]
    assert "cex_author_submit_case" in error and "--allow-edited-emit" in error
    assert not (tmp_path / "out" / "emitted_b" / "case.xlsx").exists()


def test_cli_compiles_it_only_when_told_and_warns(tmp_path):
    proc = _compile(tmp_path, "--allow-edited-emit")
    assert proc.returncode == 0, proc.stdout + proc.stderr
    assert "cex_author_emit" in proc.stderr
    assert (tmp_path / "out" / "emitted_b" / "case.xlsx").is_file()


def test_the_emit_path_itself_still_compiles_emitted_cases(tmp_path):
    """cex_author_emit 经 cex_client.skill_scripts 调 compile_excel()，不走命令行，不受拒绝影响。"""
    sys.path.insert(0, str(REPO_ROOT))
    from cex_client.skill_scripts import compile_workbook

    cases = tmp_path / "cases.json"
    cases.write_text(json.dumps(EMITTED, ensure_ascii=False), encoding="utf-8")
    result = compile_workbook(cases, tmp_path / "out")
    assert Path(result["path"]).is_file()
