import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { ClientError } from "./errors.js";
import {
  Workspace,
  fromStatePath,
  readPrivateJson,
  safeComponent,
  stateLock,
  toStatePath,
  writeFileSafely,
  writePrivateJson,
} from "./workspace.js";
import { prepare as engineEnvPrepare, localRulesPath } from "./engine_env.js";
import { canonicalJson } from "./fingerprints.js";

export const STATE_SCHEMA = "cex.author-dispatch/v1";
const _STRIP = "\ufeff\uffff";
const _INTENT_STAMP_SCHEMA = "ist.intent-stamp-status";
const _CASES_SCHEMA_NOTE = "generated by cex_author_emit from sealed mechanical cases";

function _statePath(ws: Workspace, outName: string): string {
  return path.join(ws.stateDir, "author", `${safeComponent(outName, "batch name")}.json`);
}

function _loadState(ws: Workspace, outName: string): Record<string, unknown> {
  const state = readPrivateJson(_statePath(ws, outName));
  if (!state || state.schema !== STATE_SCHEMA) {
    throw new ClientError(`no authoring dispatch for ${JSON.stringify(outName)}; call cex_author_prepare`);
  }
  return state;
}

function _saveState(ws: Workspace, state: Record<string, unknown>): void {
  writePrivateJson(_statePath(ws, String(state.out_name)), { ...state, schema: STATE_SCHEMA });
}

function _updateState(ws: Workspace, outName: string, change: (state: Record<string, unknown>) => void): Record<string, unknown> {
  const lock = stateLock(ws, "author", outName);
  try {
    const state = readPrivateJson(_statePath(ws, outName)) ?? {};
    state.out_name = state.out_name ?? outName;
    change(state);
    _saveState(ws, state);
    return state;
  } finally {
    lock.release();
  }
}

export function casesRoot(ws: Workspace, outName: string): string {
  return path.join(ws.outputsDir, safeComponent(outName, "batch name"), "cases");
}

function _sha256Bytes(raw: Buffer): string {
  return crypto.createHash("sha256").update(raw).digest("hex");
}

function _canonicalSha256(value: unknown): string {
  return _sha256Bytes(Buffer.from(canonicalJson(value), "utf8"));
}

async function _sealedBatch(ws: Workspace, outName: string): Promise<[Record<string, unknown>, string]> {
  const { _loadState: loadRecomposeState } = await import("./recompose.js");
  const rstate = loadRecomposeState(ws, outName);
  const { verify_machine_mindmap_submission_commit } = await import("../cex_core/engine/ist_core/tools/device/recompose_submission.js");
  try {
    verify_machine_mindmap_submission_commit(ws.outputsDir, String(rstate.out_name), String(rstate.dispatch_id), { expected_binding: rstate.binding as Record<string, any> | null | undefined });
  } catch (exc) {
    throw new ClientError(`the machine mindmap of ${JSON.stringify(outName)} is not sealed (${exc instanceof Error ? exc.constructor.name : "Error"}: ${exc}); call cex_recompose_seal first`);
  }
  return [rstate, path.join(ws.outputsDir, String(rstate.out_name))];
}

async function _currentSealSha(ws: Workspace, outName: string, pinned?: unknown): Promise<string> {
  engineEnvPrepare(ws, { pinned });
  const [, batch] = await _sealedBatch(ws, outName);
  const { load_machine_mindmap } = await import("../cex_core/engine/case_compiler/mindmap_contract_projector.js");
  const [, sha] = load_machine_mindmap(path.join(batch, "machine_mindmap.json"));
  return sha;
}

async function _requireCurrentSeal(ws: Workspace, state: Record<string, unknown>): Promise<void> {
  const outName = String(state.out_name);
  let current: string;
  try {
    current = await _currentSealSha(ws, outName, state.data_root);
  } catch (exc) {
    if (exc instanceof ClientError) {
      throw new ClientError(
        `authoring ${JSON.stringify(outName)} needs its recompose batch sealed, and it is not: ${exc}. cex_recompose_prepare reopens a sealed batch and removes machine_mindmap.json; call cex_recompose_seal, then cex_author_prepare, then continue`);
    }
    throw exc;
  }
  const expected = String(state.projected_machine_mindmap_sha256 ?? (state.receipt as Record<string, unknown> | undefined)?.machine_mindmap_sha256 ?? "");
  if (!expected) {
    throw new ClientError(`the authoring state of ${JSON.stringify(outName)} does not say which sealed machine mindmap it was projected from; call cex_author_prepare again`);
  }
  if (current !== expected) {
    throw new ClientError(
      `the recompose batch ${JSON.stringify(outName)} was sealed again since cex_author_prepare (the contract cards come from machine mindmap ${expected.slice(0, 12)}, the seal is now ${current.slice(0, 12)}); call cex_author_prepare to re-project the contract cards, then continue`);
  }
}

function _status(batch: string, name: string): [Record<string, unknown>, Buffer] {
  const raw = fs.readFileSync(path.join(batch, name));
  return [JSON.parse(raw.toString("utf8")), raw];
}

function _specText(root: string, specStatus: Record<string, unknown>): string | null {
  if (specStatus.status !== "bound") return null;
  const p = path.join(root, "knowledge", "data", "spec", "generations",
    safeComponent(specStatus.generation_id, "spec generation"), "docs",
    safeComponent(specStatus.name, "spec name"));
  const raw = fs.readFileSync(p);
  if (_sha256Bytes(raw) !== specStatus.sha256) {
    throw new ClientError("the bound governing spec changed after recompose; call cex_recompose_prepare again");
  }
  return raw.toString("utf8");
}

async function _manifestCases(text: string): Promise<Record<string, Record<string, unknown>>> {
  const { _extract_cases } = await import("../cex_core/engine/ist_core/tools/device/compile_prep.js");
  const roots = JSON.parse(text);
  const cases: Record<string, Record<string, unknown>> = {};
  for (const root of Array.isArray(roots) ? roots : [roots]) {
    if (typeof root !== "object" || root === null) continue;
    for (const case_ of _extract_cases(root)) {
      cases[String(case_.autoid)] = case_;
    }
  }
  return cases;
}

export async function sourceCaseSlice(case_: Record<string, unknown>, autoid: string): Promise<[Record<string, unknown>, string]> {
  const { canonical_source_case_slice, canonical_source_case_slice_sha256 } = await import("../cex_core/engine/ist_core/worker_device_context.js");
  const canonical = canonical_source_case_slice(case_, { autoid });
  return [canonical, canonical_source_case_slice_sha256(canonical, { autoid })];
}

async function _versions(info: Record<string, unknown>): Promise<[string, string, string]> {
  const { resolve_compile_manual_version } = await import("../cex_core/engine/case_compiler/criterion_author_rules.js");
  const { _inventory_version_from_device_build } = await import("../cex_core/engine/case_compiler/vendor_stdlib.js");
  const full = String(info.device_os_build ?? "");
  return [full, _inventory_version_from_device_build(full), resolve_compile_manual_version({ full_version: full })];
}

async function _project(root: string, batch: string, rstate: Record<string, unknown>, info: Record<string, unknown>, ruleRecords?: Record<string, unknown> | null): Promise<Record<string, unknown>> {
  const { fill_mechanical_fields, load_machine_mindmap, project_machine_mindmap, verbatim_failures } = await import("../cex_core/engine/case_compiler/mindmap_contract_projector.js");
  const { object_kind_closed_set, sealed_structure_failures, strip_engine_slots } = await import("../cex_core/engine/case_compiler/step_structure.js");

  const [specStatus] = _status(batch, "governing_spec_status.json");
  const [defect] = _status(batch, "defect_spec_status.json");
  const sourceRaw = fs.readFileSync(path.join(batch, "mindmap_source.json"));
  const text = sourceRaw.toString("utf8").replace(new RegExp(`^[${_STRIP}]+`), "");
  const specText = _specText(root, specStatus);
  const specName = (specStatus.status === "bound" ? specStatus.name : null) as string | null;
  const defectReceipt = typeof defect.receipt === "object" && defect.receipt !== null ? defect.receipt as Record<string, unknown> : null;
  const mmPath = path.join(batch, "machine_mindmap.json");
  const [mmData, mmSha] = load_machine_mindmap(mmPath);
  fill_mechanical_fields(mmData, text);
  const kinds = object_kind_closed_set();
  const structureBad: Record<string, string[]> = {};
  for (const case_ of (mmData.cases as unknown[]) ?? []) {
    if (typeof case_ !== "object" || case_ === null) continue;
    strip_engine_slots(case_);
    const codes = sealed_structure_failures(case_, { object_kinds: kinds });
    if (codes.length) structureBad[String((case_ as Record<string, unknown>).autoid ?? "")] = codes;
  }
  const bad = verbatim_failures(mmData, text, specText, {
    governing_spec: specName,
    governing_spec_status: String(specStatus.status),
    defect_spec_receipt: defectReceipt,
    defect_spec_status: String(defect.status),
    defect_spec_receipt_sha256: String(defect.receipt_sha256 ?? "") || null,
  });
  const [, family, manual] = await _versions(info);
  const staging = path.join(batch, `.author-projection-${crypto.randomUUID().replace(/-/g, "")}`);
  fs.mkdirSync(staging);
  fs.copyFileSync(mmPath, path.join(staging, "machine_mindmap.json"));
  const summary = project_machine_mindmap(staging, {
    quarantine: bad,
    structure_quarantine: structureBad,
    criterion_unavailable: {},
    missing_autoids: [],
    manifest_cases: null,
    expected_machine_sha256: mmSha,
    previously_owned_autoids: [],
    resolved_governing_spec: specName as string | null,
    resolved_governing_spec_status: String(specStatus.status),
    mindmap_source_sha256: rstate.source_sha256 as string,
    resolved_defect_spec_status: String(defect.status),
    resolved_defect_spec_receipt_sha256: String(defect.receipt_sha256 ?? "") || null,
    resolved_defect_spec_receipt: defectReceipt,
    mindmap_text: text,
    spec_text: specText,
    criterion_version_family: family,
    criterion_manual_version: manual,
    criterion_rule_records: ruleRecords ?? null,
  });
  return { summary, staging, machine_mindmap: mmData, machine_mindmap_sha256: mmSha, structure_quarantine: structureBad, verbatim_quarantine: bad };
}

function _publish(batch: string, staging: string): void {
  const { MACHINE_MINDMAP_DISCLOSURES_SIDECAR_NAME: SIDECAR } = require("../cex_core/engine/case_compiler/mindmap_contract_projector.js");
  const token = crypto.randomUUID().replace(/-/g, "");
  const moved: [string, string][] = [];
  try {
    for (const name of ["contracts", SIDECAR]) {
      const current = path.join(batch, name);
      if (fs.existsSync(current) && fs.lstatSync(current).isSymbolicLink()) {
        throw new ClientError(`${current} is a symlink; refusing to publish over it`);
      }
      if (fs.existsSync(current)) {
        const backup = path.join(batch, `.${name}.author-backup-${token}`);
        fs.renameSync(current, backup);
        moved.push([backup, current]);
      }
    }
    for (const name of ["contracts", SIDECAR]) {
      const src = path.join(staging, name);
      if (fs.existsSync(src)) {
        fs.renameSync(src, path.join(batch, name));
      }
    }
  } catch (e) {
    for (const [backup, current] of moved) {
      if (fs.existsSync(current)) fs.rmSync(current, { recursive: true, force: true });
      fs.renameSync(backup, current);
    }
    throw e;
  }
  for (const [backup] of moved) {
    fs.rmSync(backup, { recursive: true, force: true });
  }
}

function _receipt(batch: string, projected: Record<string, unknown>, rstate: Record<string, unknown>): Record<string, unknown> {
  const summary = projected.summary as Record<string, unknown>;
  const [specStatus, specRaw] = _status(batch, "governing_spec_status.json");
  const [defect, defectRaw] = _status(batch, "defect_spec_status.json");
  return {
    ev: "recompose_done",
    reentry_round: 0,
    written: (summary.written as unknown[]).length,
    abandoned: (summary.abandoned as unknown[]).length,
    needs_decision: (summary.needs_decision as unknown[]).length,
    disclosures: (summary.disclosures as unknown[]).length,
    quarantined: (summary.quarantined as unknown[]).length,
    bucket_counts: summary.bucket_counts,
    source_status_counts: summary.source_status_counts,
    typed_pending_autoids: summary.typed_pending,
    typed_ready_autoids: summary.typed_ready,
    provisional_spec_unknown_autoids: summary.provisional_spec_unknown_autoids,
    governing_spec: specStatus.status === "bound" ? specStatus.name : null,
    governing_spec_status: specStatus.status,
    governing_spec_sha256: specStatus.sha256,
    governing_spec_size: specStatus.size,
    governing_spec_generation_id: specStatus.generation_id,
    governing_spec_manifest_sha256: specStatus.manifest_sha256,
    governing_spec_status_sha256: _sha256Bytes(specRaw),
    defect_spec_status: defect.status,
    defect_spec_receipt_sha256: defect.receipt_sha256,
    defect_spec_status_sha256: _sha256Bytes(defectRaw),
    mindmap_source_sha256: rstate.source_sha256,
    machine_mindmap_sha256: projected.machine_mindmap_sha256,
    written_autoids: summary.written,
    abandoned_autoids: summary.abandoned,
    contract_sha256_by_autoid: summary.contract_sha256_by_autoid,
    disclosure_sha256: summary.disclosure_sha256,
    projection_sha256: summary.disclosure_sha256,
  };
}

async function _stampIntent(ws: Workspace, root: string, batch: string, caseRoot: string, aid: string, receipt: Record<string, unknown>, case_: Record<string, unknown> | undefined): Promise<Record<string, unknown>> {
  const { read_regular_nofollow } = await import("../cex_core/engine/case_compiler/_sealed_io.js");
  const { normalize_contract, write_intent_json_atomic, write_json_atomic } = await import("../cex_core/engine/case_compiler/contract_entry.js");
  const { forbidden_mechanism_intents } = await import("../cex_core/engine/case_compiler/domain_grammar.js");
  const { resolve_consistency_requirement } = await import("../cex_core/engine/ist_core/compile_engine/consistency_requirement.js");

  const caseDir = path.join(caseRoot, safeComponent(aid, "autoid"));
  const marker = path.join(caseDir, "intent_stamp_status.json");
  fs.mkdirSync(caseDir, { recursive: true });
  write_json_atomic(marker, { schema: _INTENT_STAMP_SCHEMA, autoid: aid, status: "pending" });
  if (typeof case_ !== "object" || case_ === null) {
    throw new ClientError(`case ${aid} is missing from the mindmap`);
  }
  const payload: Record<string, unknown> = {
    autoid: aid,
    title: String(case_.title ?? ""),
    step_intents: case_.step_intents ?? [],
    group_path: case_.group_path ?? [],
    source: "manifest",
    stamped_by: "engine.author",
    consistency_requirement: "required",
    consistency_binding_status: "pending",
    consistency_contract_path: null,
    consistency_contract_sha256: null,
    consistency_receipt_sha256: null,
    governing_spec_status: String(receipt.governing_spec_status ?? "unknown"),
  };
  if (receipt.governing_spec_status === "bound") {
    payload.governing_spec = receipt.governing_spec;
    payload.governing_spec_identity = {
      name: receipt.governing_spec,
      sha256: receipt.governing_spec_sha256,
      size: receipt.governing_spec_size,
      generation_id: receipt.governing_spec_generation_id,
      manifest_sha256: receipt.governing_spec_manifest_sha256,
    };
  }
  const contractPath = path.join(batch, "contracts", `${aid}.json`);
  const expected = String((receipt.contract_sha256_by_autoid as Record<string, unknown> | undefined)?.[aid] ?? "");
  const raw = read_regular_nofollow(contractPath, {
    trusted_root: ws.outputsDir,
    errorType: ClientError,
    invalid_message: "machine contract path is invalid",
    directory_message: "machine contract directory is unavailable",
    open_message: "machine contract is unavailable",
    bounds_message: "machine contract exceeds its sealed size boundary",
    changed_message: "machine contract changed while being read",
    max_bytes: 16 * 1024 * 1024,
    min_bytes: 1,
  }) as Buffer;
  if (_sha256Bytes(raw) !== expected) {
    throw new ClientError(`typed expectation contract identity drift for ${aid}`);
  }
  const contract = JSON.parse(raw.toString("utf8"));
  payload.typed_expectation_contract_sha256 = expected;
  payload.typed_expectation_contract_path = path.relative(ws.root, contractPath).split(path.sep).join("/");
  const status = String(contract.typed_assertion_status ?? "ready");
  if (!["ready", "pending"].includes(status)) {
    throw new ClientError("typed expectation contract status is invalid");
  }
  payload.typed_expectation_status = status;
  const typed: Record<string, unknown> = {};
  const claims: Record<string, unknown> = {};
  const defectClaims: Record<string, unknown> = {};
  for (const item of (normalize_contract(contract, path.basename(contractPath)).expectations as unknown[]) ?? []) {
    if (typeof item !== "object" || item === null) continue;
    const i = item as Record<string, unknown>;
    const assertion = i.assertion;
    const claim = i.author_claim;
    const defectClaim = i.defect_spec_claim;
    if (typeof assertion === "object" && assertion !== null) {
      typed[String((assertion as Record<string, unknown>).expectation_id ?? "")] = assertion;
    } else if (typeof claim === "object" && claim !== null) {
      claims[String((claim as Record<string, unknown>).expectation_id ?? "")] = claim;
    } else if (typeof defectClaim === "object" && defectClaim !== null) {
      defectClaims[String((defectClaim as Record<string, unknown>).expectation_id ?? "")] = defectClaim;
    } else {
      throw new ClientError("typed expectation entry is absent");
    }
  }
  payload.typed_expectations = typed;
  payload.author_claims = claims;
  payload.defect_spec_claims = defectClaims;
  const proof = resolve_consistency_requirement({ outputs_root: ws.outputsDir, project_root: root, batch_name: path.basename(batch), autoid: aid, facts: [receipt] });
  payload.governing_spec_status = proof.governing_spec_status;
  payload.consistency_requirement = proof.requirement;
  payload.consistency_binding_status = proof.binding_status;
  const haystack = [payload.title, ...((payload.step_intents as Record<string, unknown>[]) ?? []).map((si) => `${si.desc ?? ""} ${si.expected ?? ""}`)].join(" ").toLowerCase();
  const hits = [];
  for (const [family, patterns] of forbidden_mechanism_intents()) {
    for (const pattern of patterns) {
      if (new RegExp(pattern).test(haystack)) hits.push({ family, matched: pattern });
    }
  }
  if (hits.length) payload.forbidden_mechanism = hits.slice(0, 3);
  write_intent_json_atomic(path.join(caseDir, "intent.json"), payload);
  write_json_atomic(marker, { schema: _INTENT_STAMP_SCHEMA, autoid: aid, status: "complete" });
  return proof;
}

const SLOT_RULE = "Each expectation is redeemed by the block its expectation_binding points at. The submission gate accepts the binding only when (block kind, operator) is one of that expectation's allowed_slots: operator is asserts[assert_index].op for OBSERVE_ASSERT, the block's F for STEP, and \"\" for kinds that carry no operator.";
const _VETO_INVITATION = /这条归类是引擎裁定的，与你写的不符就可以翻掉：答「[^」]*」（键 [0-9a-f]*），下次同类编译重新裁定/;
const _VETO_NOTE = "这条归类是引擎裁定的；与你写的不符时，把你的异议告诉我，我会如实写进报告，但本客户端不能翻掉它——在服务端的判据台账改动之前，这条归类保持不变";

async function _allowedSlots(): Promise<Record<string, string[][]>> {
  const { CRITERION_TYPE_ALLOWED_SLOTS } = await import("../cex_core/engine/case_compiler/criterion_carriers.js");
  const out: Record<string, string[][]> = {};
  for (const [ctype, pairs] of Object.entries(CRITERION_TYPE_ALLOWED_SLOTS)) {
    out[ctype] = [...pairs].sort((a, b) => a[0].localeCompare(b[0]) || a[1].localeCompare(b[1])).map(([k, op]) => [String(k), String(op)]);
  }
  return out;
}

function _cardView(batch: string, aid: string, slots: Record<string, string[][]>, mmCase: Record<string, unknown> | undefined): Record<string, unknown> {
  const contract = JSON.parse(fs.readFileSync(path.join(batch, "contracts", `${aid}.json`), "utf8"));
  const expectations = [];
  for (const item of (contract.expectations as unknown[]) ?? []) {
    if (typeof item !== "object" || item === null) continue;
    const i = item as Record<string, unknown>;
    const claim = (i.author_claim ?? i.defect_spec_claim ?? {}) as Record<string, unknown>;
    const normalized = (i.normalized_claim ?? {}) as Record<string, unknown>;
    const ctype = String(normalized.criterion_type ?? "");
    expectations.push({
      expectation_id: claim.expectation_id,
      semantic_key: claim.semantic_key,
      text: i.text,
      claim_kind: claim.kind,
      criterion_type: ctype || null,
      criterion_label: normalized.criterion_label_zh,
      allowed_slots: JSON.parse(JSON.stringify(slots[ctype] ?? [])),
      authored_step: normalized.authored_step,
      fixture_mode: normalized.mode,
    });
  }
  return {
    autoid: aid,
    title: contract.intent_verbatim,
    group_path: (contract.mindmap_group as Record<string, unknown> | undefined)?.group_path,
    bucket: contract.bucket,
    author_steps: contract.author_steps,
    adapted_steps: contract.adapted_steps,
    step_structure: contract.step_structure,
    concretizations: JSON.parse(JSON.stringify(mmCase?.concretizations ?? [])),
    consistency: contract.consistency,
    device_disclosure: contract.device_disclosure,
    expectations,
    contract_path: path.join(batch, "contracts", `${aid}.json`),
  };
}

export function clientDisclosureMessage(message: string): string {
  let text = String(message ?? "").replace(_VETO_INVITATION, _VETO_NOTE);
  if (text.includes("否决并重裁")) {
    text = text.split("；").map((part) => part.includes("否决并重裁") ? _VETO_NOTE : part).join("；");
  }
  return text;
}

function _pendingView(ws: Workspace, state: Record<string, unknown>): Record<string, unknown>[] {
  const out = [];
  for (const [key, brief] of Object.entries((state.pending as Record<string, Record<string, unknown>>) ?? {}).sort()) {
    const shape = ((brief as Record<string, unknown>).shapes as Record<string, unknown>[])[0] ?? {};
    out.push({
      shape_key: key,
      members: shape.members,
      claims: ((shape.claims as Record<string, unknown>[]) ?? []).map((c: Record<string, unknown>) => ({
        autoid: c.autoid,
        expectation_id: c.expectation_id,
        original_text: c.original_text,
      })),
      criterion_types: ((brief.criterion_types as Record<string, unknown>[]) ?? []).map((row: Record<string, unknown>) => row.criterion_type),
      brief_path: fromStatePath(ws, String((state.brief_paths as Record<string, unknown>)[key])),
    });
  }
  return out;
}

async function _roundRules(state: Record<string, unknown>, manual: string): Promise<Record<string, unknown> | null> {
  const { load_author_rules, round_rule_supply } = await import("../cex_core/engine/case_compiler/criterion_author_rules.js");
  const records = (state.round_records as Record<string, any>[]) ?? [];
  if (!records.length) return null;
  return round_rule_supply(manual ? load_author_rules({ manual_version: manual }) : {}, records, { manual_version: manual });
}

async function _projectAndPublish(ws: Workspace, state: Record<string, unknown>): Promise<Record<string, unknown>> {
  const [root, info] = engineEnvPrepare(ws, { pinned: state.data_root });
  const [rstate, batch] = await _sealedBatch(ws, String(state.out_name));
  const [, , manual] = await _versions(info);
  const projected = await _project(root, batch, rstate, info, await _roundRules(state, manual));
  const staging = String(projected.staging);
  const summary = projected.summary as Record<string, unknown>;
  try {
    if (summary.criterion_pending) {
      return _stopForCriteria(ws, state, projected, batch, manual);
    }
    const receiptCore = {
      ev: "recompose_done",
      machine_mindmap_sha256: summary.machine_mindmap_sha256,
      written_autoids: summary.written,
      contract_sha256_by_autoid: summary.contract_sha256_by_autoid,
      disclosure_sha256: summary.disclosure_sha256,
    };
    const { load_disclosure_projection } = await import("../cex_core/engine/case_compiler/mindmap_contract_projector.js");
    const precheck = load_disclosure_projection(staging, receiptCore);
    if (precheck.status !== "valid") {
      throw new ClientError(`the staged projection does not load: ${precheck.reason} ${precheck.diagnostic}`);
    }
    _publish(batch, staging);
  } finally {
    fs.rmSync(staging, { recursive: true, force: true });
  }
  const receipt = _receipt(batch, projected, rstate);
  const text = fs.readFileSync(path.join(batch, "mindmap_source.json"), "utf8").replace(new RegExp(`^[${_STRIP}]+`), "");
  const manifestCases = await _manifestCases(text);
  const caseRoot = casesRoot(ws, String(state.out_name));
  const stamped: Record<string, unknown> = {};
  for (const aid of summary.written as string[]) {
    const proof = await _stampIntent(ws, root, batch, caseRoot, aid, receipt, manifestCases[aid]);
    const [, sliceSha] = await sourceCaseSlice(manifestCases[aid], aid);
    stamped[aid] = { consistency_requirement: proof.requirement, source_case_slice_sha256: sliceSha };
  }
  const capability = info.capability ?? {};
  const contracts = receipt.contract_sha256_by_autoid as Record<string, string>;

  const publish = (current: Record<string, unknown>) => {
    const sealed = current.sealed !== undefined ? current.sealed : state.sealed;
    Object.assign(current, {
      phase: "published",
      receipt,
      cases: stamped,
      pending: {},
      projected_machine_mindmap_sha256: summary.machine_mindmap_sha256,
      data_root: toStatePath(ws, root),
      bundle_id: info.bundle_id,
      capability,
      cases_root: toStatePath(ws, caseRoot),
      round_records: current.round_records ?? state.round_records ?? [],
      sealed: Object.fromEntries(Object.entries((sealed as Record<string, Record<string, unknown>>) ?? {}).filter(([aid, record]) => contracts[aid] === record.contract_sha256)),
    });
  };
  _updateState(ws, String(state.out_name), publish);

  const { load: bedLoad, loadServices: bedLoadServices, factsView } = await import("./bed.js");
  const topology = bedLoad(ws) ?? {};
  const disclosures = ((summary.disclosures as Record<string, unknown>[]) ?? []).map((item) => {
    const out: Record<string, unknown> = {};
    for (const k of ["autoid", "code", "message", "criterion_type"]) {
      if (item[k] !== undefined && item[k] !== null) out[k] = k === "message" ? clientDisclosureMessage(String(item[k])) : item[k];
    }
    return out;
  });
  const disclosuresPath = path.join(batch, "author_disclosures.json");
  writeFileSafely(ws.root, disclosuresPath, JSON.stringify(disclosures, null, 1));
  const slots = await _allowedSlots();
  const sealedMm = JSON.parse(fs.readFileSync(path.join(batch, "machine_mindmap.json"), "utf8"));
  const mmCases: Record<string, Record<string, unknown>> = {};
  for (const case_ of (sealedMm.cases as unknown[]) ?? []) {
    if (typeof case_ === "object" && case_ !== null) {
      mmCases[String((case_ as Record<string, unknown>).autoid ?? "")] = case_ as Record<string, unknown>;
    }
  }
  return {
    ok: true,
    out_name: state.out_name,
    phase: "published",
    cases: (summary.written as string[]).map((aid) => _cardView(batch, aid, slots, mmCases[aid])),
    slot_rule: SLOT_RULE,
    quarantined: summary.quarantined,
    needs_decision: summary.needs_decision,
    abandoned: summary.abandoned,
    disclosures: { count: disclosures.length, path: disclosuresPath },
    bed: Object.keys(topology).length ? await factsView(topology, bedLoadServices(ws)) : null,
    blocks_schema: path.join(root, "knowledge", "data", "compile_ref", "blocks_schema.json"),
    next: "Write one mechanical case per case (blocks language, see the skill's references/authoring.md) and submit each with cex_author_submit_case; then cex_author_emit.",
  };
}

async function _stopForCriteria(ws: Workspace, state: Record<string, unknown>, projected: Record<string, unknown>, batch: string, manual: string): Promise<Record<string, unknown>> {
  const { build_engine_adjudication_brief, serialize_engine_adjudication_brief, split_engine_adjudication_briefs } = await import("../cex_core/engine/case_compiler/criterion_author_rules.js");
  const { load_projection } = await import("../cex_core/engine/case_compiler/criterion_normalization.js");

  const summary = projected.summary as Record<string, unknown>;
  const staging = String(projected.staging);
  const contracts: Record<string, Record<string, any>> = {};
  for (const aid of (summary.written as string[]) ?? []) {
    contracts[aid] = JSON.parse(fs.readFileSync(path.join(staging, "contracts", `${aid}.json`), "utf8"));
  }
  const brief = build_engine_adjudication_brief(summary.criterion_pending as Record<string, any>[], {
    projection: load_projection(),
    machine_mindmap: projected.machine_mindmap as Record<string, any>,
    contracts,
    manual_version: manual || null,
  });
  if (brief === null) {
    throw new ClientError("criterion pending shapes have no adjudication envelope");
  }
  const directory = path.join(batch, "criterion_briefs");
  const pending: Record<string, unknown> = {};
  const paths: Record<string, unknown> = {};
  for (const shapeBrief of split_engine_adjudication_briefs(brief)) {
    const key = String((shapeBrief.shapes as Record<string, unknown>[])[0].shape_key);
    const p = path.join(directory, `${safeComponent(key.slice(0, 16), "shape key")}.json`);
    writeFileSafely(ws.root, p, serialize_engine_adjudication_brief(shapeBrief));
    pending[key] = shapeBrief;
    paths[key] = toStatePath(ws, p);
  }
  const stop = (current: Record<string, unknown>) => {
    Object.assign(current, {
      phase: "criterion_pending",
      pending,
      brief,
      brief_paths: paths,
      data_root: state.data_root,
      round_records: current.round_records ?? state.round_records ?? [],
      sealed: current.sealed !== undefined ? current.sealed : state.sealed ?? {},
      projected_machine_mindmap_sha256: projected.machine_mindmap_sha256,
    });
  };
  const newState = _updateState(ws, String(state.out_name), stop);
  return {
    ok: true,
    out_name: newState.out_name,
    phase: "criterion_pending",
    pending_shapes: _pendingView(ws, newState),
    next: "Adjudicate each shape: read its brief_path, pick one criterion_type from the brief's catalogue and call cex_criterion_record (see the skill's references/criterion.md). Contracts are published after the last one.",
  };
}

export async function prepare(ws: Workspace, outName: string): Promise<Record<string, unknown>> {
  const { _loadState: loadRecomposeState } = await import("./recompose.js");
  const pinned = loadRecomposeState(ws, outName).data_root;
  const [root, info] = engineEnvPrepare(ws, { pinned });
  if (info.topology === null) {
    throw new ClientError("no bed topology in this workspace; call cex_bed_topology first (the authoring gates read the bed facts)");
  }
  if (((info.command_tree as Record<string, unknown> | undefined)?.store as Record<string, unknown> | undefined)?.status !== "ready") {
    throw new ClientError("the synced bundle carries no command tree generation; the authoring gates need it. Ask the publisher to republish, then call cex_sync");
  }
  const [rstate] = await _sealedBatch(ws, outName);
  const previous = readPrivateJson(_statePath(ws, String(rstate.out_name))) ?? {};
  const state = {
    schema: STATE_SCHEMA,
    out_name: rstate.out_name,
    round_records: previous.round_records ?? [],
    sealed: previous.sealed ?? {},
    data_root: toStatePath(ws, root),
  };
  return _projectAndPublish(ws, state);
}

export async function criterionRecord(ws: Workspace, outName: string, shapeKey: string, judgment: unknown): Promise<Record<string, unknown>> {
  const state = _loadState(ws, outName);
  await _requireCurrentSeal(ws, state);
  const [, info] = engineEnvPrepare(ws, { pinned: state.data_root });
  const brief = ((state.pending as Record<string, unknown>)?.[String(shapeKey ?? "")] ?? null) as Record<string, any> | null;
  if (brief === null) {
    throw new ClientError(`shape ${JSON.stringify(shapeKey)} is not pending; pending: ${JSON.stringify(Object.keys(state.pending ?? {}).sort())}`);
  }
  const { CriterionAuthorRuleError, parse_engine_adjudication_result, persist_engine_adjudications } = await import("../cex_core/engine/case_compiler/criterion_author_rules.js");
  const reply = typeof judgment === "string" ? judgment : JSON.stringify(judgment);
  let decisions: unknown;
  try {
    decisions = parse_engine_adjudication_result(reply, { brief: brief as Record<string, any> });
  } catch (exc: unknown) {
    if (exc instanceof CriterionAuthorRuleError) {
      return {
        ok: false,
        status: "rejected",
        error: (exc as Error).message,
        legal_form: "One JSON object with criterion_type (copied from the brief's catalogue), rationale (English) and disclosure (Chinese); optionally manual_anchor_ids / tree_context_ids / behaviour_classes. No other keys.",
      };
    }
    throw exc;
  }
  const [, , manual] = await _versions(info);
  const records = persist_engine_adjudications(decisions as Record<string, any>[], { brief: state.brief as Record<string, any>, manual_version: manual || null });
  const local = localRulesPath(ws);
  fs.mkdirSync(path.dirname(local), { recursive: true });
  const lock = stateLock(ws, "criterion-rules");
  try {
    const known = new Set<string>();
    if (fs.existsSync(local)) {
      for (const line of fs.readFileSync(local, "utf8").split("\n").filter(Boolean)) {
        try { known.add(String(JSON.parse(line).rule_sha256)); } catch {}
      }
    }
    const append: string[] = [];
    for (const record of records) {
      if (!known.has(String(record.rule_sha256))) {
        append.push(JSON.stringify(record, Object.keys(record).sort()) + "\n");
      }
    }
    if (append.length) fs.appendFileSync(local, append.join(""), "utf8");
  } finally {
    lock.release();
  }
  const recordShape = (current: Record<string, unknown>) => {
    current.round_records = [...((current.round_records as unknown[]) ?? []), ...records];
    current.pending = Object.fromEntries(Object.entries((current.pending as Record<string, unknown>) ?? {}).filter(([k]) => k !== shapeKey));
  };
  const newState = _updateState(ws, outName, recordShape);
  const decided = records.map((r: Record<string, unknown>) => ({
    rule_id: r.rule_id,
    criterion_type: (r.output as Record<string, unknown>)?.criterion_type,
    disclosure: r.disclosure,
  }));
  if (Object.keys(newState.pending ?? {}).length) {
    return { ok: true, status: "recorded", decided, pending_shapes: _pendingView(ws, newState) };
  }
  return { status: "recorded", decided, ...(await _projectAndPublish(ws, newState)) };
}

function _reject(autoid: string, violations: Record<string, unknown>[], advisories: unknown[] = []): Record<string, unknown> {
  const { _violations_with_legal_forms } = require("../cex_core/engine/ist_core/tools/device/mechanical_case_submit_tool.js");
  return { ok: false, status: "rejected", autoid, violations: _violations_with_legal_forms(violations), advisories: [...advisories] };
}

function _violation(code: string, locus: string, detail: string, gate = "dispatch_binding"): Record<string, string> {
  return { gate, code, locus, detail };
}

export async function submitCase(ws: Workspace, outName: string, mechanicalCase: unknown): Promise<Record<string, unknown>> {
  const state = _loadState(ws, outName);
  if (state.phase !== "published") {
    throw new ClientError("contracts are not published yet; finish cex_author_prepare (and any cex_criterion_record) first");
  }
  await _requireCurrentSeal(ws, state);
  const [root] = engineEnvPrepare(ws, { pinned: state.data_root });
  let body: Record<string, unknown>;
  if (typeof mechanicalCase === "string") {
    try {
      body = JSON.parse(mechanicalCase);
    } catch (exc) {
      return _reject("", [_violation("payload_invalid_json", "mechanical_case", String(exc), "mechanical_case_body")]);
    }
  } else if (typeof mechanicalCase === "object" && mechanicalCase !== null && !Array.isArray(mechanicalCase)) {
    body = { ...(mechanicalCase as Record<string, unknown>) };
  } else {
    return _reject("", [_violation("not_an_object", "mechanical_case", "mechanical_case must be one JSON object", "mechanical_case_body")]);
  }
  const aid = String(body.autoid ?? "");
  const receipt = state.receipt as Record<string, unknown>;
  if (!(receipt.written_autoids as string[]).includes(aid)) {
    return _reject(aid, [_violation("autoid_not_dispatched", "autoid", `${JSON.stringify(aid)} is not a contracted case of ${outName}; contracted: ${JSON.stringify(receipt.written_autoids)}`)]);
  }
  if ("seal" in body) {
    return _reject(aid, [_violation("self_reported_seal", "seal", "do not include seal; the engine mints it after the gates pass", "mechanical_case_body")]);
  }
  const { NOT_APPLICABLE } = await import("../cex_core/engine/ist_core/compile_engine/consistency_requirement.js");
  const caseState = (state.cases as Record<string, unknown>)?.[aid] as Record<string, unknown> | undefined;
  if (caseState?.consistency_requirement !== NOT_APPLICABLE) {
    return _reject(aid, [_violation("consistency_stage_unavailable", "consistency_requirement", "this case is bound to a governing specification, which requires the case/spec consistency verdict before a mechanical case; that stage is not available in this client. Recompose with spec='none' to compile without the specification.")]);
  }
  const batch = path.join(ws.outputsDir, String(state.out_name));
  const contractRaw = fs.readFileSync(path.join(batch, "contracts", `${aid}.json`));
  const contractSha = _sha256Bytes(contractRaw);
  if (contractSha !== (receipt.contract_sha256_by_autoid as Record<string, unknown>)[aid]) {
    return _reject(aid, [_violation("frozen_contract_drift", "contracts", "the contract card changed after it was published; call cex_author_prepare again")]);
  }
  const contract = JSON.parse(contractRaw.toString("utf8"));
  const { mint_and_land_mechanical_case } = await import("../cex_core/engine/case_compiler/mechanical_case.js");
  const { AUDIENCE_WORKER, gate_report_digest, run_mechanical_case_gate } = await import("../cex_core/engine/case_compiler/mechanical_case_gate.js");
  const { configured_device_os_build } = await import("../cex_core/engine/case_compiler/vendor_stdlib.js");
  const { MECHANICAL_CASE_SIDECAR_NAME } = await import("../cex_core/engine/engine_managed_outputs.js");
  const { _canonicalize_submission_blocks, _stamp_engine_binding, unique_exempt_blocks_submit } = await import("../cex_core/engine/ist_core/tools/device/mechanical_case_submit_tool.js");

  const capability = (state.capability as Record<string, unknown>) ?? {};
  const session = {
    capability_generation_id: capability.generation_id ?? "",
    capability_projection_sha256: capability.projection_sha256 ?? "",
    authored_round: 1,
    source_manifest_ref: "",
    source_manifest_sha256: "",
  };
  if (body.binding === undefined) body.binding = {};
  if (body.escape_hatches === undefined) body.escape_hatches = [];
  const [stampedBody, violations] = _stamp_engine_binding(body, {
    contract,
    contract_sha256: contractSha,
    consistency_contract_sha256: null,
    session,
    project_root: root,
  });
  if (violations.length) return _reject(aid, violations);
  const [canonBody, error] = _canonicalize_submission_blocks(stampedBody);
  if (canonBody === null) return _reject(aid, [_violation("ssl_cert_load_invalid", "blocks", error, "mechanical_case_body")]);
  const undetermined = (canonBody.blocks as Record<string, unknown>[]).filter((b) => (b.answerer as Record<string, unknown>)?.kind === "undetermined").map((b) => (b.answerer as Record<string, unknown>).note);
  if (undetermined.length) {
    return { ok: false, status: "needs_user_decision", autoid: aid, claims: undetermined, detail: "an observation names no answerer; nothing is sealed. Ask the user who answers it, or rewrite the block with a determined answerer." };
  }
  _requireIdentityTable(canonBody);
  const text = fs.readFileSync(path.join(batch, "mindmap_source.json"), "utf8").replace(new RegExp(`^[${_STRIP}]+`), "");
  const [slice, sliceSha] = await sourceCaseSlice((await _manifestCases(text))[aid], aid);
  const caseRoot = await _ensureCasesRoot(ws, state, root, batch, text);
  let ok: boolean, report: Record<string, unknown>;
  try {
    [ok, report] = run_mechanical_case_gate(canonBody, contract, {
      contract_sha256: contractSha,
      device_build: configured_device_os_build(),
      outputs_root: caseRoot,
      consistency_contract: null,
      consistency_contract_sha256: "",
      consistency_required: false,
      source_case_slice: slice,
      source_case_slice_sha256: sliceSha,
    });
  } catch (exc) {
    return _reject(aid, [_violation("gate_uncomputable", "mechanical_case", `the mechanical case could not be gated: ${exc instanceof Error ? exc.constructor.name : "Error"}: ${exc}`, "mechanical_case_body")]);
  }
  const advisories = ((report.advisories as Record<string, unknown>[]) ?? []).map((item) => ({ gate: String(item.gate ?? ""), code: String(item.code ?? ""), locus: String(item.locus ?? ""), detail: String(item.detail ?? "") }));
  if (!ok) {
    const found = [];
    for (const item of (report.hard_rejects as Record<string, unknown>[]) ?? []) {
      if (item.audience !== AUDIENCE_WORKER) continue;
      const finding: Record<string, unknown> = { gate: String(item.gate ?? ""), code: String(item.code ?? ""), locus: String(item.locus ?? ""), detail: String(item.detail ?? "") };
      if (Array.isArray(item.expectation_ids)) finding.expectation_ids = item.expectation_ids.map(String).filter(Boolean);
      found.push(finding);
    }
    const others = ((report.hard_rejects as Record<string, unknown>[]) ?? []).filter((i) => i.audience !== AUDIENCE_WORKER);
    if (others.length && !found.length) {
      found.push(...others.map((item) => ({ gate: String(item.gate ?? ""), code: String(item.code ?? ""), locus: String(item.locus ?? ""), detail: String(item.detail ?? "") })));
    }
    return _reject(aid, found, advisories);
  }
  const exempt = unique_exempt_blocks_submit(canonBody);
  if (exempt !== null) return _reject(aid, [exempt], advisories);
  const measurements = report.measurements as Record<string, unknown>;
  const artifact = path.join(caseRoot, aid, MECHANICAL_CASE_SIDECAR_NAME);
  const republished: boolean[] = [];
  const lock = stateLock(ws, "author-case", `${state.out_name}/${aid}`);
  let current: Record<string, unknown>;
  try {
    const minted = mint_and_land_mechanical_case({ ...canonBody }, artifact, {
      capabilities_used: measurements.capabilities_used as string[],
      expanded_step_count: Number(measurements.expanded_step_count),
      check_point_count: Number(measurements.check_point_count),
      gate_report_sha256: gate_report_digest(report),
    });
    if (minted.document === null) return _reject(aid, [_violation(minted.code, "case", minted.detail, "seal")], advisories);
    const seal = (minted.document as Record<string, unknown>).seal as Record<string, unknown>;
    const record = (cur: Record<string, unknown>) => {
      const contracts = ((cur.receipt as Record<string, unknown>)?.contract_sha256_by_autoid as Record<string, unknown>) ?? {};
      if (cur.phase !== "published" || contracts[aid] !== contractSha) {
        republished.push(true);
        return;
      }
      cur.sealed = cur.sealed ?? {};
      (cur.sealed as Record<string, unknown>)[aid] = {
        artifact: toStatePath(ws, artifact),
        mechanical_case_sha256: seal.mechanical_case_sha256,
        contract_sha256: contractSha,
      };
    };
    current = _updateState(ws, String(state.out_name), record);
  } finally {
    lock.release();
  }
  if (republished.length) {
    return _reject(aid, [_violation("contracts_republished", "contracts", "cex_author_prepare re-published the contract cards while this case was being checked; nothing was recorded. Read the new card and submit the case again")], advisories);
  }
  const written = ((current.receipt as Record<string, unknown>)?.written_autoids as string[]) ?? [];
  const remaining = written.filter((a) => !((current.sealed as Record<string, unknown>) ?? {})[a]);
  return {
    ok: true,
    status: "sealed",
    autoid: aid,
    artifact,
    mechanical_case_sha256: (current.sealed as Record<string, Record<string, unknown>>)[aid].mechanical_case_sha256,
    expanded_step_count: measurements.expanded_step_count,
    check_point_count: measurements.check_point_count,
    advisories,
    remaining_autoids: remaining,
  };
}

async function _precedentBlocks(blocks: unknown): Promise<number[] | null> {
  const { expand_blocks } = await import("../cex_core/engine/case_compiler/blocks.js");
  const blockList = Array.isArray(blocks) ? blocks : [];
  let steps: unknown, prov: unknown, error: unknown;
  try {
    [steps, prov, error] = expand_blocks(blockList);
  } catch {
    return null;
  }
  if (error || !prov) return null;
  if (!(prov as unknown[]).some((item) => typeof item === "object" && item !== null && ((item as Record<string, unknown>).source as Record<string, unknown>)?.kind === "precedent")) return [];
  const cites = (ref: unknown) => String(ref ?? "").split(":")[0].trim() === "precedent";
  const out = blockList.map((block, i) => {
    if (typeof block !== "object" || block === null) return -1;
    const b = block as Record<string, unknown>;
    if (cites(b.ref)) return i;
    if ((b.asserts as Record<string, unknown>[] ?? []).some((a) => cites(a.ref))) return i;
    return -1;
  }).filter((i) => i >= 0);
  return out.length ? out : [-1];
}

async function _identityTableMissing(): Promise<string> {
  const { IdentityListUnavailable } = await import("../cex_core/engine/_root.js");
  const { DENIED_668_AUTOIDS } = await import("../cex_core/engine/case_compiler/package_advisories.js");
  try {
    void DENIED_668_AUTOIDS.size;
  } catch (exc) {
    if (exc instanceof IdentityListUnavailable) return exc.message;
    throw exc;
  }
  return "";
}

async function _requireIdentityTable(body: Record<string, unknown>): Promise<void> {
  const blocks = await _precedentBlocks(body.blocks);
  if (!blocks?.length) return;
  const missing = await _identityTableMissing();
  if (!missing) return;
  const where = blocks[0] !== -1 ? `block(s) ${JSON.stringify(blocks.filter((b) => b >= 0))}` : "an expanded step";
  throw new ClientError(
    `${where} cite a precedent source, and cex_author_submit_case cannot accept one without the engine's identity table (the denied-package case numbers every precedent is checked against), which this installation does not have: ${missing}. Cite the manual, a footprint or the stamped intent instead, or ask the maintainer to install the identity table`);
}

async function _ensureCasesRoot(ws: Workspace, state: Record<string, unknown>, root: string, batch: string, text: string): Promise<string> {
  const caseRoot = casesRoot(ws, String(state.out_name));
  if (state.cases_root) return caseRoot;
  const lock = stateLock(ws, "author-migrate", String(state.out_name));
  try {
    const current = readPrivateJson(_statePath(ws, String(state.out_name))) ?? {};
    if (!current.cases_root) {
      const receipt = (state.receipt as Record<string, unknown>) ?? {};
      const manifestCases = await _manifestCases(text);
      for (const aid of (receipt.written_autoids as string[]) ?? []) {
        await _stampIntent(ws, root, batch, caseRoot, aid, receipt, manifestCases[aid]);
      }
      _updateState(ws, String(state.out_name), (cur) => { cur.cases_root = toStatePath(ws, caseRoot); });
    }
  } finally {
    lock.release();
  }
  state.cases_root = toStatePath(ws, caseRoot);
  return caseRoot;
}

function _stepSource(prov: Record<string, unknown>): Record<string, string> {
  const source = (prov.source as Record<string, unknown>) ?? {};
  const kind = String(source.kind ?? "").trim();
  const ref = String(source.locator ?? source.ref ?? "").trim();
  return kind && ref ? { kind, ref } : {};
}

export async function expandCase(p: string): Promise<[Record<string, unknown>, Record<string, unknown>[]]> {
  const { expand_blocks, lower_derived_assertions } = await import("../cex_core/engine/case_compiler/blocks.js");
  const { load_mechanical_case } = await import("../cex_core/engine/case_compiler/mechanical_case.js");
  const [case_] = load_mechanical_case(p);
  const body: Record<string, unknown> = { ...case_, schema: case_.schema_ } as unknown as Record<string, unknown>;
  delete body.schema_;
  const [steps, prov, error] = expand_blocks([...(body.blocks as Record<string, any>[])]);
  if (error || steps === null) throw new ClientError(`${p}: blocks do not expand: ${error}`);
  const [lowered, prov2, error2] = lower_derived_assertions(steps, prov);
  if (error2 || lowered === null) throw new ClientError(`${p}: derived assertions do not lower: ${error2}`);
  const out: Record<string, unknown>[] = [];
  const init = ((body.init_commands as string[]) ?? []).map(String).filter(Boolean).join("\n");
  if (init) out.push({ E: "APV_0", F: "cmds_config", G: init, desc: "case 自包含前置配置" });
  for (let i = 0; i < lowered.length; i++) {
    const step = lowered[i];
    const item = (prov2 as Record<string, unknown>[])?.[i] ?? {};
    const row: Record<string, unknown> = { E: step.E, F: step.F, G: step.G ?? "", desc: step.desc ?? "" };
    for (const key of ["H", "I"]) {
      if (step[key] !== undefined && step[key] !== null && step[key] !== "") row[key] = step[key];
    }
    if (String(step.E ?? "").trim() === "check_point") {
      const source = _stepSource(item);
      if (Object.keys(source).length) row.source = source;
    }
    out.push(row);
  }
  return [body, out];
}

async function _sealedCase(ws: Workspace, aid: string, record: Record<string, unknown>, caseRoot: string): Promise<[Record<string, unknown>, Record<string, unknown>[], Buffer | null]> {
  const p = fromStatePath(ws, record.artifact);
  let body: Record<string, unknown>, steps: Record<string, unknown>[];
  let raw: Buffer;
  try {
    [body, steps] = await expandCase(p);
    raw = fs.readFileSync(p);
  } catch (exc) {
    throw new ClientError(`the sealed file is unreadable or invalid (${exc instanceof Error ? exc.constructor.name : "Error"}: ${exc})`);
  }
  const actual = String((body.seal as Record<string, unknown>)?.mechanical_case_sha256 ?? "");
  if (actual !== String(record.mechanical_case_sha256 ?? "")) {
    throw new ClientError(`the sealed file now holds mechanical case ${actual.slice(0, 12)}, not the ${String(record.mechanical_case_sha256 ?? "").slice(0, 12)} sealed for this batch (overwritten by another batch or edited)`);
  }
  const target = path.join(caseRoot, aid, path.basename(p));
  return [body, steps, p !== target ? raw : null];
}

async function _relocateSealed(ws: Workspace, outName: string, aid: string, record: Record<string, unknown>, raw: Buffer, caseRoot: string): Promise<void> {
  const source = fromStatePath(ws, record.artifact);
  const target = path.join(caseRoot, aid, path.basename(source));
  const lock = stateLock(ws, "author-case", `${outName}/${aid}`);
  try {
    const current = ((readPrivateJson(_statePath(ws, outName)) ?? {}).sealed as Record<string, Record<string, unknown>>)?.[aid];
    if (!current || current.artifact !== record.artifact || current.mechanical_case_sha256 !== record.mechanical_case_sha256) return;
    writeFileSafely(ws.root, target, raw);
    _updateState(ws, outName, (state) => {
      (state.sealed as Record<string, Record<string, unknown>>)[aid].artifact = toStatePath(ws, target);
    });
  } finally {
    lock.release();
  }
}

export async function emit(ws: Workspace, outName: string): Promise<Record<string, unknown>> {
  const state = _loadState(ws, outName);
  await _requireCurrentSeal(ws, state);
  engineEnvPrepare(ws, { pinned: state.data_root });
  const receipt = (state.receipt as Record<string, unknown>) ?? {};
  const sealed = (state.sealed as Record<string, Record<string, unknown>>) ?? {};
  const contracts = (receipt.contract_sha256_by_autoid as Record<string, string>) ?? {};
  const caseRoot = casesRoot(ws, String(state.out_name));
  const missing: string[] = [];
  const drifted: { autoid: string; reason: string }[] = [];
  const relocations: Record<string, Buffer> = {};
  const cases = [];
  for (const aid of (receipt.written_autoids as string[]) ?? []) {
    if (!(aid in sealed)) {
      missing.push(aid);
      continue;
    }
    let body: Record<string, unknown>, steps: Record<string, unknown>[], relocate: Buffer | null;
    try {
      [body, steps, relocate] = await _sealedCase(ws, aid, sealed[aid], caseRoot);
    } catch (exc) {
      drifted.push({ autoid: aid, reason: String(exc) });
      continue;
    }
    if ((body.binding as Record<string, unknown>)?.contract_sha256 !== contracts[aid]) {
      missing.push(aid);
      continue;
    }
    if (relocate !== null) relocations[aid] = relocate;
    const description = (body.description as Record<string, unknown>) ?? {};
    cases.push({ autoid: aid, priority: "P1", description: String(description.intent_verbatim ?? ""), steps });
  }
  for (const [aid, raw] of Object.entries(relocations)) {
    await _relocateSealed(ws, String(state.out_name), aid, sealed[aid], raw, caseRoot);
  }
  if (!cases.length) {
    throw new ClientError("no sealed mechanical case to emit; submit cases with cex_author_submit_case first" + (drifted.length ? ` (not emitted: ${JSON.stringify(drifted)})` : ""));
  }
  const batch = path.join(ws.outputsDir, String(state.out_name));
  const doc = { batch: state.out_name, cases, _generated: _CASES_SCHEMA_NOTE };
  const casesPath = path.join(batch, "cases.json");
  writeFileSafely(ws.root, casesPath, JSON.stringify(doc, null, 1));
  const { compileWorkbook, verifyWorkbook } = await import("./skill_scripts.js");
  const result = await compileWorkbook(casesPath, ws.outputsDir);
  const verify = await verifyWorkbook(String(result.path));
  const complete = !missing.length && !drifted.length;
  const out: Record<string, unknown> = {
    ok: complete && Boolean(result.ok) && Number(verify.fail ?? 0) === 0,
    xlsx: result.path,
    cases_json: casesPath,
    emitted_autoids: cases.map((c) => c.autoid),
    not_sealed_autoids: missing,
    not_emitted: drifted,
    verify: { pass: verify.pass, fail: verify.fail, failures: verify.failures },
  };
  if (!complete) {
    out.error = `the workbook holds ${cases.length} of ${(receipt.written_autoids as string[])?.length ?? 0} contracted cases` +
      (missing.length ? `; not sealed yet: ${JSON.stringify(missing)}` : "") +
      (drifted.length ? `; sealed file replaced, not emitted: ${JSON.stringify(drifted.map((d) => d.autoid))}` : "") +
      ". Submit those cases with cex_author_submit_case and emit again, or tell the user which cases are missing before running this workbook.";
  }
  return out;
}



