"""编写阶段在客户端的编排：已密封的机械脑图 → 契约卡 → 机械用例 → 出件用例。

InfoTest 里这一段由编译引擎做：recompose 节点的投影段把机械脑图投成每案一张契约卡
（期望原文 + 引擎裁定的判据类型 + 允许的断言块与算子），author 节点给每案盖 intent 章、派
compile-worker 写机械用例（块语言）并经 submit_mechanical_case 的提交规则闸封存，emit 把
封存的用例展开成工作簿。客户端没有引擎，这里把那层薄胶水按原顺序移植过来；判据（契约投影、
判据台账与裁定复核、提交规则闸、块展开、派生断言收据）一律调 cex_core.engine 抽取来的同一批
函数，不重写：

- prepare：nodes.py `recompose` 的投影段（fill_mechanical_fields → 结构/逐字隔离 →
  project_machine_mindmap → 判据待裁定就停下 → 预检 → 原子发布 contracts/ 与披露旁车 →
  recompose_done 回执）+ `_stamp_intent`（每案 intent.json，写 author_claims）。
- criterion_record：引擎把待裁定的判据形状交给 criterion-adjudicator fork；客户端把同一份
  单形状 brief 交给当前模型，回执经 parse_engine_adjudication_result 机械复核、
  persist_engine_adjudications 入台账（同时记进工作区，换数据包后接着用），全部裁完重投影。
- submit_case：submit_mechanical_case 的判定链——冻结契约、盖引擎绑定、SSL_CERT_LOAD 标准库
  降级、提交规则闸（run_mechanical_case_gate）、豁免账、铸封落盘。
- emit：expand_blocks + lower_derived_assertions 展开封存的机械用例（与引擎 emit 同一展开），
  出 cases.json（断言步带引擎给的出处），交给 compile_excel 出件。

与引擎的差别（都只在这层胶水里）：
- 不移植 worker 会话：修补轮省略 expectation_binding / escape_hatches 的续传、重复拒收计数、
  会话准入与事实账都没有；每次提交都要带完整的八段主体，按整份从头判。
- 规格一致性（case 与管辖规格书的一致性裁决，scenario 1）没有移植：管辖规格书绑定时
  consistency_requirement=required，提交如实拒绝并说明；recompose 时 spec='none' 走不适用。
- answerer 为 undetermined 的观察块不经引擎写用户裁决账，直接如实返回待用户裁决，不封存。
- 客户端的产物根是工作区 compile_outputs/（引擎是 workspace/outputs/），批目录与每案目录的
  相对布局不变；intent.json 里的契约路径相对工作区根记。
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import uuid
from pathlib import Path
from types import SimpleNamespace
from typing import Any

from . import engine_env
from .errors import ClientError
from .workspace import Workspace, read_private_json, safe_component, write_private_json

STATE_SCHEMA = "cex.author-dispatch/v1"
_STRIP = "﻿￿"
_INTENT_STAMP_SCHEMA = "ist.intent-stamp-status"
_CASES_SCHEMA_NOTE = "generated by cex_author_emit from sealed mechanical cases"


# ── 状态 ────────────────────────────────────────────────────────────────


def _state_path(ws: Workspace, out_name: str) -> Path:
    return ws.state_dir / "author" / f"{safe_component(out_name, 'batch name')}.json"


def _load_state(ws: Workspace, out_name: str) -> dict[str, Any]:
    state = read_private_json(_state_path(ws, out_name))
    if not state or state.get("schema") != STATE_SCHEMA:
        raise ClientError(f"no authoring dispatch for {out_name!r}; call cex_author_prepare")
    return state


def _save_state(ws: Workspace, state: dict[str, Any]) -> None:
    write_private_json(_state_path(ws, state["out_name"]), {**state, "schema": STATE_SCHEMA})


def _sha256_bytes(raw: bytes) -> str:
    return hashlib.sha256(raw).hexdigest()


def _canonical_sha256(value: Any) -> str:
    return _sha256_bytes(json.dumps(value, ensure_ascii=False, sort_keys=True,
                                    separators=(",", ":")).encode("utf-8"))


# ── 输入：已密封的机械脑图与它的来源状态 ──────────────────────────────────


def _sealed_batch(ws: Workspace, out_name: str) -> tuple[dict[str, Any], Path]:
    from . import recompose

    rstate = recompose._load_state(ws, out_name)
    from cex_core.engine.ist_core.tools.device.recompose_submission import (
        verify_machine_mindmap_submission_commit,
    )

    try:
        verify_machine_mindmap_submission_commit(ws.outputs_dir, rstate["out_name"],
                                                 rstate["dispatch_id"],
                                                 expected_binding=rstate["binding"])
    except Exception as exc:  # noqa: BLE001 — 引擎的密封核对：任何不过都等于没密封
        raise ClientError(f"the machine mindmap of {out_name!r} is not sealed "
                          f"({type(exc).__name__}: {exc}); call cex_recompose_seal first") from None
    return rstate, ws.outputs_dir / rstate["out_name"]


def _status(batch: Path, name: str) -> tuple[dict[str, Any], bytes]:
    raw = (batch / name).read_bytes()
    return json.loads(raw.decode("utf-8")), raw


def _spec_text(root: Path, spec_status: dict[str, Any]) -> str | None:
    if spec_status.get("status") != "bound":
        return None
    path = (root / "knowledge" / "data" / "spec" / "generations"
            / safe_component(spec_status.get("generation_id"), "spec generation")
            / "docs" / safe_component(spec_status.get("name"), "spec name"))
    raw = path.read_bytes()
    if _sha256_bytes(raw) != spec_status.get("sha256"):
        raise ClientError("the bound governing spec changed after recompose; call "
                          "cex_recompose_prepare again")
    return raw.decode("utf-8", errors="replace")


def _manifest_cases(text: str) -> dict[str, dict[str, Any]]:
    """InfoTest compile_prep 从脑图抽出的每案切片（标题、step_intents、分组路径）。"""
    from cex_core.engine.ist_core.tools.device import compile_prep

    roots = json.loads(text)
    cases: dict[str, dict[str, Any]] = {}
    for root in roots if isinstance(roots, list) else [roots]:
        if isinstance(root, dict):
            for case in compile_prep._extract_cases(root):
                cases[str(case["autoid"])] = case
    return cases


def source_case_slice(case: dict[str, Any], autoid: str) -> tuple[dict[str, Any], str]:
    """worker_device_context.canonical_source_case_slice 与它的摘要（同一规范化）。"""
    from cex_core.engine.ist_core.worker_device_context import (
        canonical_source_case_slice,
        canonical_source_case_slice_sha256,
    )

    canonical = canonical_source_case_slice(case, autoid=autoid)
    return canonical, canonical_source_case_slice_sha256(canonical, autoid=autoid)


def _versions(info: dict[str, Any]) -> tuple[str, str, str]:
    """(完整版本, 判据版本族 如 10.5, 手册版本 如 10.5.0)。"""
    from cex_core.engine.case_compiler.criterion_author_rules import (
        resolve_compile_manual_version,
    )
    from cex_core.engine.case_compiler.vendor_stdlib import (
        _inventory_version_from_device_build,
    )

    full = str(info.get("device_os_build") or "")
    return (full, _inventory_version_from_device_build(full),
            resolve_compile_manual_version(full_version=full))


# ── 投影（nodes.py recompose 的投影段） ──────────────────────────────────


def _project(root: Path, batch: Path, rstate: dict[str, Any], info: dict[str, Any],
             *, rule_records: dict | None) -> dict[str, Any]:
    from cex_core.engine.case_compiler.mindmap_contract_projector import (
        fill_mechanical_fields,
        load_machine_mindmap,
        project_machine_mindmap,
        verbatim_failures,
    )
    from cex_core.engine.case_compiler.step_structure import (
        object_kind_closed_set,
        sealed_structure_failures,
        strip_engine_slots,
    )

    spec_status, _ = _status(batch, "governing_spec_status.json")
    defect, _ = _status(batch, "defect_spec_status.json")
    source_raw = (batch / "mindmap_source.json").read_bytes()
    text = source_raw.decode("utf-8").lstrip(_STRIP)
    spec_text = _spec_text(root, spec_status)
    spec_name = spec_status.get("name") if spec_status.get("status") == "bound" else None
    defect_receipt = defect.get("receipt") if isinstance(defect.get("receipt"), dict) else None
    mm_path = batch / "machine_mindmap.json"
    mm_data, mm_sha = load_machine_mindmap(mm_path)
    fill_mechanical_fields(mm_data, text)
    kinds = object_kind_closed_set()
    structure_bad: dict[str, list[str]] = {}
    for case in mm_data.get("cases") or []:
        if not isinstance(case, dict):
            continue
        strip_engine_slots(case)
        codes = sealed_structure_failures(case, object_kinds=kinds)
        if codes:
            structure_bad[str(case.get("autoid") or "")] = codes
    bad = verbatim_failures(
        mm_data, text, spec_text, governing_spec=spec_name,
        governing_spec_status=str(spec_status["status"]), defect_spec_receipt=defect_receipt,
        defect_spec_status=str(defect["status"]),
        defect_spec_receipt_sha256=str(defect.get("receipt_sha256") or "") or None)
    _full, family, manual = _versions(info)
    staging = batch / f".author-projection-{uuid.uuid4().hex}"
    staging.mkdir()
    shutil.copyfile(mm_path, staging / "machine_mindmap.json")
    summary = project_machine_mindmap(
        staging, quarantine=bad, structure_quarantine=structure_bad, criterion_unavailable={},
        missing_autoids=[], manifest_cases=None, expected_machine_sha256=mm_sha,
        previously_owned_autoids=[], resolved_governing_spec=spec_name,
        resolved_governing_spec_status=str(spec_status["status"]),
        mindmap_source_sha256=rstate["source_sha256"],
        resolved_defect_spec_status=str(defect["status"]),
        resolved_defect_spec_receipt_sha256=str(defect.get("receipt_sha256") or "") or None,
        resolved_defect_spec_receipt=defect_receipt, mindmap_text=text, spec_text=spec_text,
        criterion_version_family=family, criterion_manual_version=manual,
        criterion_rule_records=rule_records or None)
    return {"summary": summary, "staging": staging, "machine_mindmap": mm_data,
            "machine_mindmap_sha256": mm_sha, "structure_quarantine": structure_bad,
            "verbatim_quarantine": bad}


def _publish(batch: Path, staging: Path) -> None:
    """nodes.py `_publish_staged_projection`：contracts/ 与披露旁车整体换进批目录。"""
    from cex_core.engine.case_compiler.mindmap_contract_projector import (
        MACHINE_MINDMAP_DISCLOSURES_SIDECAR_NAME as SIDECAR,
    )

    token = uuid.uuid4().hex
    moved: list[tuple[Path, Path]] = []
    try:
        for name in ("contracts", SIDECAR):
            current = batch / name
            if current.is_symlink():
                raise ClientError(f"{current} is a symlink; refusing to publish over it")
            if current.exists():
                backup = batch / f".{name}.author-backup-{token}"
                os.rename(current, backup)
                moved.append((backup, current))
        for name in ("contracts", SIDECAR):
            if (staging / name).exists():
                os.rename(staging / name, batch / name)
    except BaseException:
        for backup, current in moved:
            if current.exists():
                shutil.rmtree(current) if current.is_dir() else current.unlink()
            os.rename(backup, current)
        raise
    for backup, _current in moved:
        shutil.rmtree(backup) if backup.is_dir() else backup.unlink()


def _receipt(batch: Path, projected: dict[str, Any], rstate: dict[str, Any]) -> dict[str, Any]:
    """nodes.py 在投影发布后记下的 recompose_done 事实（后续一致性要求、出处核对都认它）。"""
    summary = projected["summary"]
    spec_status, spec_raw = _status(batch, "governing_spec_status.json")
    defect, defect_raw = _status(batch, "defect_spec_status.json")
    return {
        "ev": "recompose_done", "reentry_round": 0,
        "written": len(summary["written"]), "abandoned": len(summary["abandoned"]),
        "needs_decision": len(summary["needs_decision"]),
        "disclosures": len(summary["disclosures"]), "quarantined": len(summary["quarantined"]),
        "bucket_counts": summary["bucket_counts"],
        "source_status_counts": summary["source_status_counts"],
        "typed_pending_autoids": list(summary["typed_pending"]),
        "typed_ready_autoids": list(summary["typed_ready"]),
        "provisional_spec_unknown_autoids": list(summary["provisional_spec_unknown_autoids"]),
        "governing_spec": spec_status.get("name") if spec_status.get("status") == "bound" else None,
        "governing_spec_status": spec_status["status"],
        "governing_spec_sha256": spec_status.get("sha256"),
        "governing_spec_size": spec_status.get("size"),
        "governing_spec_generation_id": spec_status.get("generation_id"),
        "governing_spec_manifest_sha256": spec_status.get("manifest_sha256"),
        "governing_spec_status_sha256": _sha256_bytes(spec_raw),
        "defect_spec_status": defect["status"],
        "defect_spec_receipt_sha256": defect.get("receipt_sha256"),
        "defect_spec_status_sha256": _sha256_bytes(defect_raw),
        "mindmap_source_sha256": rstate["source_sha256"],
        "machine_mindmap_sha256": projected["machine_mindmap_sha256"],
        "written_autoids": list(summary["written"]),
        "abandoned_autoids": list(summary["abandoned"]),
        "contract_sha256_by_autoid": dict(summary["contract_sha256_by_autoid"]),
        "disclosure_sha256": summary["disclosure_sha256"],
        "projection_sha256": summary["disclosure_sha256"],
    }


def _stamp_intent(ws: Workspace, root: Path, batch: Path, aid: str, receipt: dict[str, Any],
                  case: dict[str, Any] | None) -> dict[str, Any]:
    """nodes.py `_stamp_intent`：每案 intent.json（author_claims 是断言兑现 Author 期望的出处）。"""
    from cex_core.engine.case_compiler._sealed_io import read_regular_nofollow
    from cex_core.engine.case_compiler.contract_entry import (
        normalize_contract,
        write_intent_json_atomic,
        write_json_atomic,
    )
    from cex_core.engine.case_compiler.domain_grammar import forbidden_mechanism_intents
    from cex_core.engine.ist_core.compile_engine.consistency_requirement import (
        resolve_consistency_requirement,
    )

    case_dir = ws.outputs_dir / aid
    marker = case_dir / "intent_stamp_status.json"
    case_dir.mkdir(parents=True, exist_ok=True)
    write_json_atomic(marker, {"schema": _INTENT_STAMP_SCHEMA, "autoid": aid, "status": "pending"})
    if not isinstance(case, dict):
        raise ClientError(f"case {aid} is missing from the mindmap")
    payload: dict[str, Any] = {
        "autoid": aid, "title": str(case.get("title") or ""),
        "step_intents": case.get("step_intents") or [], "group_path": case.get("group_path") or [],
        "source": "manifest", "stamped_by": "engine.author",
        "consistency_requirement": "required", "consistency_binding_status": "pending",
        "consistency_contract_path": None, "consistency_contract_sha256": None,
        "consistency_receipt_sha256": None,
        "governing_spec_status": str(receipt.get("governing_spec_status") or "unknown"),
    }
    if receipt.get("governing_spec_status") == "bound":
        payload["governing_spec"] = receipt.get("governing_spec")
        payload["governing_spec_identity"] = {
            key: receipt.get(f"governing_spec_{field}") for key, field in (
                ("name", "name"), ("sha256", "sha256"), ("size", "size"),
                ("generation_id", "generation_id"), ("manifest_sha256", "manifest_sha256"))}
        payload["governing_spec_identity"]["name"] = receipt.get("governing_spec")
    contract_path = batch / "contracts" / f"{aid}.json"
    expected = str((receipt.get("contract_sha256_by_autoid") or {}).get(aid) or "")
    raw = read_regular_nofollow(
        contract_path, trusted_root=ws.outputs_dir, error_type=ClientError,
        invalid_message="machine contract path is invalid",
        directory_message="machine contract directory is unavailable",
        open_message="machine contract is unavailable",
        bounds_message="machine contract exceeds its sealed size boundary",
        changed_message="machine contract changed while being read",
        max_bytes=16 * 1024 * 1024, min_bytes=1)
    if _sha256_bytes(raw) != expected:
        raise ClientError(f"typed expectation contract identity drift for {aid}")
    contract = json.loads(raw.decode("utf-8"))
    payload["typed_expectation_contract_sha256"] = expected
    payload["typed_expectation_contract_path"] = contract_path.relative_to(ws.root).as_posix()
    status = str(contract.get("typed_assertion_status") or "ready")
    if status not in ("ready", "pending"):
        raise ClientError("typed expectation contract status is invalid")
    payload["typed_expectation_status"] = status
    typed, claims, defect_claims = {}, {}, {}
    for item in normalize_contract(contract, contract_path.name).get("expectations") or []:
        assertion = item.get("assertion") if isinstance(item, dict) else None
        claim = item.get("author_claim") if isinstance(item, dict) else None
        defect_claim = item.get("defect_spec_claim") if isinstance(item, dict) else None
        if isinstance(assertion, dict):
            typed[str(assertion.get("expectation_id") or "")] = assertion
        elif isinstance(claim, dict):
            claims[str(claim.get("expectation_id") or "")] = claim
        elif isinstance(defect_claim, dict):
            defect_claims[str(defect_claim.get("expectation_id") or "")] = defect_claim
        else:
            raise ClientError("typed expectation entry is absent")
    payload.update({"typed_expectations": typed, "author_claims": claims,
                    "defect_spec_claims": defect_claims})
    proof = resolve_consistency_requirement(outputs_root=ws.outputs_dir, project_root=root,
                                            batch_name=batch.name, autoid=aid, facts=[receipt])
    payload["governing_spec_status"] = proof["governing_spec_status"]
    payload["consistency_requirement"] = proof["requirement"]
    payload["consistency_binding_status"] = proof["binding_status"]
    haystack = " ".join([payload["title"]] + [
        f"{si.get('desc') or ''} {si.get('expected') or ''}"
        for si in payload["step_intents"] if isinstance(si, dict)]).lower()
    hits = [{"family": family, "matched": pattern}
            for family, patterns in forbidden_mechanism_intents()
            for pattern in patterns if re.search(pattern, haystack)]
    if hits:
        payload["forbidden_mechanism"] = hits[:3]
    write_intent_json_atomic(case_dir / "intent.json", payload)
    write_json_atomic(marker, {"schema": _INTENT_STAMP_SCHEMA, "autoid": aid, "status": "complete"})
    return proof


# ── 给写手看的契约卡与判据待裁定视图 ─────────────────────────────────────


def _criterion_language() -> dict[str, dict[str, Any]]:
    from cex_core.engine.case_compiler.criterion_normalization import load_projection

    return {str(row.get("criterion_type") or ""): row
            for row in load_projection().get("criterion_types") or [] if isinstance(row, dict)}


def _card_view(batch: Path, aid: str, language: dict[str, dict[str, Any]]) -> dict[str, Any]:
    contract = json.loads((batch / "contracts" / f"{aid}.json").read_text(encoding="utf-8"))
    expectations = []
    for item in contract.get("expectations") or []:
        if not isinstance(item, dict):
            continue
        claim = item.get("author_claim") or item.get("defect_spec_claim") or {}
        normalized = item.get("normalized_claim") or {}
        ctype = str(normalized.get("criterion_type") or "")
        row = language.get(ctype) or {}
        expectations.append({
            "expectation_id": claim.get("expectation_id"), "semantic_key": claim.get("semantic_key"),
            "text": item.get("text"), "claim_kind": claim.get("kind"),
            "criterion_type": ctype or None, "criterion_label": normalized.get("criterion_label_zh"),
            "allowed_block_kinds": row.get("block_kinds"), "allowed_operators": row.get("operators"),
            "authored_step": normalized.get("authored_step"),
            "fixture_mode": normalized.get("mode"),
        })
    return {"autoid": aid, "title": contract.get("intent_verbatim"),
            "group_path": (contract.get("mindmap_group") or {}).get("group_path"),
            "bucket": contract.get("bucket"), "author_steps": contract.get("author_steps"),
            "adapted_steps": contract.get("adapted_steps"),
            "step_structure": contract.get("step_structure"),
            "consistency": contract.get("consistency"),
            "device_disclosure": contract.get("device_disclosure"),
            "expectations": expectations,
            "contract_path": str(batch / "contracts" / f"{aid}.json")}


def _pending_view(state: dict[str, Any]) -> list[dict[str, Any]]:
    out = []
    for key, brief in sorted((state.get("pending") or {}).items()):
        shape = (brief.get("shapes") or [{}])[0]
        out.append({"shape_key": key, "members": shape.get("members"),
                    "claims": [{"autoid": c.get("autoid"), "expectation_id": c.get("expectation_id"),
                                "original_text": c.get("original_text")}
                               for c in shape.get("claims") or []],
                    "criterion_types": [row.get("criterion_type") for row in brief.get("criterion_types") or []],
                    "brief_path": state["brief_paths"][key]})
    return out


# ── prepare / criterion_record ────────────────────────────────────────────


def _round_rules(state: dict[str, Any], manual: str) -> dict | None:
    from cex_core.engine.case_compiler.criterion_author_rules import (
        load_author_rules,
        round_rule_supply,
    )

    records = state.get("round_records") or []
    if not records:
        return None
    return round_rule_supply(load_author_rules(manual_version=manual) if manual else {},
                             records, manual_version=manual)


def _project_and_publish(ws: Workspace, state: dict[str, Any]) -> dict[str, Any]:
    root, info = engine_env.prepare(ws)
    rstate, batch = _sealed_batch(ws, state["out_name"])
    _full, _family, manual = _versions(info)
    projected = _project(root, batch, rstate, info, rule_records=_round_rules(state, manual))
    staging, summary = projected["staging"], projected["summary"]
    try:
        if summary.get("criterion_pending"):
            return _stop_for_criteria(ws, state, projected, batch, manual)
        receipt_core = {"ev": "recompose_done",
                        "machine_mindmap_sha256": summary["machine_mindmap_sha256"],
                        "written_autoids": list(summary["written"]),
                        "contract_sha256_by_autoid": dict(summary["contract_sha256_by_autoid"]),
                        "disclosure_sha256": summary["disclosure_sha256"]}
        from cex_core.engine.case_compiler.mindmap_contract_projector import (
            load_disclosure_projection,
        )

        precheck = load_disclosure_projection(staging, receipt_core)
        if precheck.get("status") != "valid":
            raise ClientError(f"the staged projection does not load: {precheck.get('reason')} "
                              f"{precheck.get('diagnostic')}")
        _publish(batch, staging)
    finally:
        shutil.rmtree(staging, ignore_errors=True)
    receipt = _receipt(batch, projected, rstate)
    text = (batch / "mindmap_source.json").read_bytes().decode("utf-8").lstrip(_STRIP)
    manifest_cases = _manifest_cases(text)
    stamped = {}
    for aid in summary["written"]:
        proof = _stamp_intent(ws, root, batch, aid, receipt, manifest_cases.get(aid))
        _slice, slice_sha = source_case_slice(manifest_cases[aid], aid)
        stamped[aid] = {"consistency_requirement": proof["requirement"],
                        "source_case_slice_sha256": slice_sha}
    capability = info.get("capability") or {}
    # 重投影后契约卡逐字节没变的案，已封存的机械用例仍然有效；变了的要重新提交
    contracts = receipt["contract_sha256_by_autoid"]
    sealed = {aid: record for aid, record in (state.get("sealed") or {}).items()
              if contracts.get(aid) == record.get("contract_sha256")}
    state.update({"phase": "published", "receipt": receipt, "cases": stamped, "pending": {},
                  "data_root": str(root), "bundle_id": info.get("bundle_id"),
                  "capability": capability, "sealed": sealed})
    _save_state(ws, state)
    language = _criterion_language()
    from . import bed

    topology = bed.load(ws) or {}
    disclosures = [{k: item.get(k) for k in ("autoid", "code", "message", "criterion_type")
                    if item.get(k) is not None} for item in summary["disclosures"]]
    disclosures_path = batch / "author_disclosures.json"
    disclosures_path.write_text(json.dumps(disclosures, ensure_ascii=False, indent=1),
                                encoding="utf-8")
    return {
        "ok": True, "out_name": state["out_name"], "phase": "published",
        "cases": [_card_view(batch, aid, language) for aid in summary["written"]],
        "quarantined": summary["quarantined"], "needs_decision": summary["needs_decision"],
        "abandoned": summary["abandoned"],
        # 给用户看的披露（判据归类、重组提案）落盘，最终报告照这份写；编写本身不需要它们
        "disclosures": {"count": len(disclosures), "path": str(disclosures_path)},
        "bed": bed.facts_view(topology) if topology else None,
        "blocks_schema": str(root / "knowledge" / "data" / "compile_ref" / "blocks_schema.json"),
        "next": ("Write one mechanical case per case (blocks language, see the skill's "
                 "references/authoring.md) and submit each with cex_author_submit_case; "
                 "then cex_author_emit."),
    }


def _stop_for_criteria(ws: Workspace, state: dict[str, Any], projected: dict[str, Any],
                       batch: Path, manual: str) -> dict[str, Any]:
    """判据有未裁定的形状：按引擎的同一份 brief 拆成单形状，交给模型裁定。"""
    from cex_core.engine.case_compiler.criterion_author_rules import (
        build_engine_adjudication_brief,
        serialize_engine_adjudication_brief,
        split_engine_adjudication_briefs,
    )
    from cex_core.engine.case_compiler.criterion_normalization import load_projection

    summary, staging = projected["summary"], projected["staging"]
    contracts = {}
    for aid in summary.get("written") or []:
        card = staging / "contracts" / f"{aid}.json"
        contracts[str(aid)] = json.loads(card.read_text(encoding="utf-8"))
    brief = build_engine_adjudication_brief(
        summary["criterion_pending"], projection=load_projection(),
        machine_mindmap=projected["machine_mindmap"], contracts=contracts,
        manual_version=manual or None)
    if brief is None:
        raise ClientError("criterion pending shapes have no adjudication envelope")
    directory = batch / "criterion_briefs"
    directory.mkdir(exist_ok=True)
    pending, paths = {}, {}
    for shape_brief in split_engine_adjudication_briefs(brief):
        key = str(shape_brief["shapes"][0]["shape_key"])
        path = directory / f"{key[:16]}.json"
        path.write_text(serialize_engine_adjudication_brief(shape_brief), encoding="utf-8")
        pending[key], paths[key] = shape_brief, str(path)
    state.update({"phase": "criterion_pending", "pending": pending, "brief": brief,
                  "brief_paths": paths})
    _save_state(ws, state)
    return {"ok": True, "out_name": state["out_name"], "phase": "criterion_pending",
            "pending_shapes": _pending_view(state),
            "next": ("Adjudicate each shape: read its brief_path, pick one criterion_type from the "
                     "brief's catalogue and call cex_criterion_record (see the skill's "
                     "references/criterion.md). Contracts are published after the last one.")}


def prepare(ws: Workspace, out_name: str) -> dict[str, Any]:
    _root, info = engine_env.prepare(ws)
    if info.get("topology") is None:
        raise ClientError("no bed topology in this workspace; call cex_bed_topology first "
                          "(the authoring gates read the bed facts)")
    if (info.get("command_tree") or {}).get("store", {}).get("status") != "ready":
        raise ClientError("the synced bundle carries no command tree generation; the authoring "
                          "gates need it. Ask the publisher to republish, then call cex_sync")
    rstate, _batch = _sealed_batch(ws, out_name)
    previous = read_private_json(_state_path(ws, rstate["out_name"])) or {}
    state = {"schema": STATE_SCHEMA, "out_name": rstate["out_name"],
             "round_records": previous.get("round_records") or [],
             "sealed": previous.get("sealed") or {}}
    return _project_and_publish(ws, state)


def criterion_record(ws: Workspace, out_name: str, shape_key: str, judgment: Any) -> dict[str, Any]:
    state = _load_state(ws, out_name)
    _root, info = engine_env.prepare(ws)
    brief = (state.get("pending") or {}).get(str(shape_key or ""))
    if brief is None:
        raise ClientError(f"shape {shape_key!r} is not pending; pending: "
                          f"{sorted(state.get('pending') or {})}")
    from cex_core.engine.case_compiler.criterion_author_rules import (
        CriterionAuthorRuleError,
        parse_engine_adjudication_result,
        persist_engine_adjudications,
    )

    reply = judgment if isinstance(judgment, str) else json.dumps(judgment, ensure_ascii=False)
    try:
        decisions = parse_engine_adjudication_result(reply, brief=brief)
    except CriterionAuthorRuleError as exc:
        return {"ok": False, "status": "rejected", "error": str(exc),
                "legal_form": ("One JSON object with criterion_type (copied from the brief's "
                               "catalogue), rationale (English) and disclosure (Chinese); "
                               "optionally manual_anchor_ids / tree_context_ids / "
                               "behaviour_classes. No other keys.")}
    _full, _family, manual = _versions(info)
    records = persist_engine_adjudications(decisions, brief=state["brief"],
                                           manual_version=manual or None)
    local = engine_env.local_rules_path(ws)
    local.parent.mkdir(parents=True, exist_ok=True)
    known = set()
    if local.is_file():
        known = {json.loads(line).get("rule_sha256") for line in
                 local.read_text(encoding="utf-8").splitlines() if line.strip()}
    with open(local, "a", encoding="utf-8") as stream:
        for record in records:
            if record.get("rule_sha256") not in known:
                stream.write(json.dumps(record, ensure_ascii=False, sort_keys=True) + "\n")
    state["round_records"] = [*(state.get("round_records") or []), *records]
    state["pending"] = {k: v for k, v in state["pending"].items() if k != shape_key}
    _save_state(ws, state)
    decided = [{"rule_id": r.get("rule_id"), "criterion_type": (r.get("output") or {}).get("criterion_type"),
                "disclosure": r.get("disclosure")} for r in records]
    if state["pending"]:
        return {"ok": True, "status": "recorded", "decided": decided,
                "pending_shapes": _pending_view(state)}
    return {"status": "recorded", "decided": decided, **_project_and_publish(ws, state)}


# ── submit_case（submit_mechanical_case 的判定链） ─────────────────────────


def _reject(autoid: str, violations: list[dict[str, Any]], advisories=()) -> dict[str, Any]:
    from cex_core.engine.ist_core.tools.device.mechanical_case_submit_tool import (
        _violations_with_legal_forms,
    )

    return {"ok": False, "status": "rejected", "autoid": autoid,
            "violations": _violations_with_legal_forms(violations),
            "advisories": list(advisories)}


def _violation(code: str, locus: str, detail: str, gate: str = "dispatch_binding") -> dict[str, str]:
    return {"gate": gate, "code": code, "locus": locus, "detail": detail}


def submit_case(ws: Workspace, out_name: str, mechanical_case: Any) -> dict[str, Any]:
    state = _load_state(ws, out_name)
    if state.get("phase") != "published":
        raise ClientError("contracts are not published yet; finish cex_author_prepare "
                          "(and any cex_criterion_record) first")
    root, _info = engine_env.prepare(ws)
    if isinstance(mechanical_case, str):
        try:
            mechanical_case = json.loads(mechanical_case)
        except ValueError as exc:
            return _reject("", [_violation("payload_invalid_json", "mechanical_case", str(exc),
                                           gate="mechanical_case_body")])
    if not isinstance(mechanical_case, dict):
        return _reject("", [_violation("not_an_object", "mechanical_case",
                                       "mechanical_case must be one JSON object",
                                       gate="mechanical_case_body")])
    body = dict(mechanical_case)
    aid = str(body.get("autoid") or "")
    receipt = state["receipt"]
    if aid not in (receipt.get("written_autoids") or []):
        return _reject(aid, [_violation("autoid_not_dispatched", "autoid",
                                        f"{aid!r} is not a contracted case of {out_name}; "
                                        f"contracted: {receipt.get('written_autoids')}")])
    if "seal" in body:
        return _reject(aid, [_violation("self_reported_seal", "seal",
                                        "do not include seal; the engine mints it after the gates pass",
                                        gate="mechanical_case_body")])
    from cex_core.engine.ist_core.compile_engine.consistency_requirement import (
        NOT_APPLICABLE,
    )

    case_state = (state.get("cases") or {}).get(aid) or {}
    if case_state.get("consistency_requirement") != NOT_APPLICABLE:
        return _reject(aid, [_violation(
            "consistency_stage_unavailable", "consistency_requirement",
            "this case is bound to a governing specification, which requires the case/spec "
            "consistency verdict before a mechanical case; that stage is not available in this "
            "client. Recompose with spec='none' to compile without the specification.")])
    batch = ws.outputs_dir / state["out_name"]
    contract_raw = (batch / "contracts" / f"{aid}.json").read_bytes()
    contract_sha = _sha256_bytes(contract_raw)
    if contract_sha != receipt["contract_sha256_by_autoid"].get(aid):
        return _reject(aid, [_violation("frozen_contract_drift", "contracts",
                                        "the contract card changed after it was published; call "
                                        "cex_author_prepare again")])
    contract = json.loads(contract_raw.decode("utf-8"))
    from cex_core.engine.case_compiler.mechanical_case import (
        mint_and_land_mechanical_case,
    )
    from cex_core.engine.case_compiler.mechanical_case_gate import (
        AUDIENCE_WORKER,
        gate_report_digest,
        run_mechanical_case_gate,
    )
    from cex_core.engine.case_compiler.vendor_stdlib import configured_device_os_build
    from cex_core.engine.engine_managed_outputs import MECHANICAL_CASE_SIDECAR_NAME
    from cex_core.engine.ist_core.tools.device.mechanical_case_submit_tool import (
        _canonicalize_submission_blocks,
        _stamp_engine_binding,
        unique_exempt_blocks_submit,
    )

    capability = state.get("capability") or {}
    session = SimpleNamespace(capability_generation_id=capability.get("generation_id") or "",
                              capability_projection_sha256=capability.get("projection_sha256") or "",
                              authored_round=1, source_manifest_ref="", source_manifest_sha256="")
    if body.get("binding") is None:
        body["binding"] = {}
    if body.get("escape_hatches") is None:
        # 引擎的提交工具同样把省略的 escape_hatches 当空数组（没有 STEP 块时本来就是空的）
        body["escape_hatches"] = []
    body, violations = _stamp_engine_binding(body, contract=contract, contract_sha256=contract_sha,
                                             consistency_contract_sha256=None, session=session,
                                             project_root=root)
    if violations:
        return _reject(aid, violations)
    body, error = _canonicalize_submission_blocks(body)
    if body is None:
        return _reject(aid, [_violation("ssl_cert_load_invalid", "blocks", error,
                                        gate="mechanical_case_body")])
    undetermined = [block.get("answerer", {}).get("note") for block in body.get("blocks") or []
                    if isinstance(block, dict) and isinstance(block.get("answerer"), dict)
                    and block["answerer"].get("kind") == "undetermined"]
    if undetermined:
        return {"ok": False, "status": "needs_user_decision", "autoid": aid,
                "claims": undetermined,
                "detail": "an observation names no answerer; nothing is sealed. Ask the user who "
                          "answers it, or rewrite the block with a determined answerer."}
    text = (batch / "mindmap_source.json").read_bytes().decode("utf-8").lstrip(_STRIP)
    slice_, slice_sha = source_case_slice(_manifest_cases(text)[aid], aid)
    try:
        ok, report = run_mechanical_case_gate(
            body, contract, contract_sha256=contract_sha, device_build=configured_device_os_build(),
            outputs_root=ws.outputs_dir, consistency_contract=None, consistency_contract_sha256="",
            consistency_required=False, source_case_slice=slice_, source_case_slice_sha256=slice_sha)
    except (TypeError, ValueError, RecursionError) as exc:
        return _reject(aid, [_violation("gate_uncomputable", "mechanical_case",
                                        f"the mechanical case could not be gated: {type(exc).__name__}: {exc}",
                                        gate="mechanical_case_body")])
    advisories = [{k: str(item.get(k) or "") for k in ("gate", "code", "locus", "detail")}
                  for item in report.get("advisories") or []]
    if not ok:
        found = []
        for item in report.get("hard_rejects") or []:
            if item.get("audience") != AUDIENCE_WORKER:
                continue
            finding = {k: str(item.get(k) or "") for k in ("gate", "code", "locus", "detail")}
            if isinstance(item.get("expectation_ids"), list):
                finding["expectation_ids"] = [str(v) for v in item["expectation_ids"] if str(v)]
            found.append(finding)
        others = [item for item in report.get("hard_rejects") or []
                  if item.get("audience") != AUDIENCE_WORKER]
        if others and not found:
            found = [{k: str(item.get(k) or "") for k in ("gate", "code", "locus", "detail")}
                     for item in others]
        return _reject(aid, found, advisories)
    exempt = unique_exempt_blocks_submit(body)
    if exempt is not None:
        return _reject(aid, [exempt], advisories)
    measurements = report["measurements"]
    minted = mint_and_land_mechanical_case(
        dict(body), ws.outputs_dir / aid / MECHANICAL_CASE_SIDECAR_NAME,
        capabilities_used=list(measurements["capabilities_used"]),
        expanded_step_count=int(measurements["expanded_step_count"]),
        check_point_count=int(measurements["check_point_count"]),
        gate_report_sha256=gate_report_digest(report))
    if minted.document is None:
        return _reject(aid, [_violation(minted.code, "case", minted.detail, gate="seal")], advisories)
    seal = minted.document["seal"]
    artifact = ws.outputs_dir / aid / MECHANICAL_CASE_SIDECAR_NAME
    state.setdefault("sealed", {})[aid] = {"artifact": str(artifact),
                                           "mechanical_case_sha256": seal["mechanical_case_sha256"],
                                           "contract_sha256": contract_sha}
    _save_state(ws, state)
    remaining = [a for a in receipt["written_autoids"] if a not in state["sealed"]]
    return {"ok": True, "status": "sealed", "autoid": aid, "artifact": str(artifact),
            "mechanical_case_sha256": seal["mechanical_case_sha256"],
            "expanded_step_count": measurements["expanded_step_count"],
            "check_point_count": measurements["check_point_count"],
            "advisories": advisories, "remaining_autoids": remaining}


# ── emit ─────────────────────────────────────────────────────────────────


def _step_source(prov: dict[str, Any]) -> dict[str, str]:
    source = prov.get("source") if isinstance(prov.get("source"), dict) else {}
    kind = str(source.get("kind") or "").strip()
    ref = str(source.get("locator") or source.get("ref") or "").strip()
    return {"kind": kind, "ref": ref} if kind and ref else {}


def expand_case(path: Path) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    """封存的机械用例 → 工作簿步骤（与引擎 emit 同一展开：块 → 步骤 → 派生断言降级）。"""
    from cex_core.engine.case_compiler.blocks import (
        expand_blocks,
        lower_derived_assertions,
    )
    from cex_core.engine.case_compiler.mechanical_case import load_mechanical_case

    case, _sha = load_mechanical_case(path)
    body = case.model_dump(mode="python", by_alias=True)
    steps, prov, error = expand_blocks(list(body["blocks"]))
    if error or steps is None:
        raise ClientError(f"{path}: blocks do not expand: {error}")
    steps, prov, error = lower_derived_assertions(steps, prov)
    if error or steps is None:
        raise ClientError(f"{path}: derived assertions do not lower: {error}")
    out = []
    init = "\n".join(str(c) for c in body.get("init_commands") or [] if str(c).strip())
    if init:
        # 引擎 emit（merge_case_producer_rules）同样把本案前置放成第一步
        out.append({"E": "APV_0", "F": "cmds_config", "G": init, "desc": "case 自包含前置配置"})
    for step, item in zip(steps, prov or [{}] * len(steps), strict=False):
        row = {"E": step.get("E"), "F": step.get("F"), "G": step.get("G", ""),
               "desc": step.get("desc") or ""}
        for key in ("H", "I"):
            if step.get(key) not in (None, ""):
                row[key] = step[key]
        if str(step.get("E") or "").strip() == "check_point":
            source = _step_source(item or {})
            if source:
                row["source"] = source
        out.append(row)
    return body, out


def emit(ws: Workspace, out_name: str) -> dict[str, Any]:
    state = _load_state(ws, out_name)
    engine_env.prepare(ws)
    receipt = state.get("receipt") or {}
    sealed = state.get("sealed") or {}
    missing = [aid for aid in receipt.get("written_autoids") or [] if aid not in sealed]
    cases = []
    for aid in receipt.get("written_autoids") or []:
        if aid not in sealed:
            continue
        body, steps = expand_case(Path(sealed[aid]["artifact"]))
        if (body.get("binding") or {}).get("contract_sha256") != \
                (receipt.get("contract_sha256_by_autoid") or {}).get(aid):
            missing.append(aid)  # 封存时的契约卡已不是现在这张：要按新卡重新提交
            continue
        description = body.get("description") or {}
        cases.append({"autoid": aid, "priority": "P1",
                      "description": str(description.get("intent_verbatim") or ""),
                      "steps": steps})
    if not cases:
        raise ClientError("no sealed mechanical case to emit; submit cases with "
                          "cex_author_submit_case first")
    batch = ws.outputs_dir / state["out_name"]
    doc = {"batch": state["out_name"], "cases": cases, "_generated": _CASES_SCHEMA_NOTE}
    cases_path = batch / "cases.json"
    cases_path.write_text(json.dumps(doc, ensure_ascii=False, indent=1), encoding="utf-8")
    from .skill_scripts import compile_workbook, verify_workbook

    result = compile_workbook(cases_path, ws.outputs_dir)
    verify = verify_workbook(Path(result["path"]))
    return {"ok": bool(result.get("ok")) and verify.get("fail") == 0,
            "xlsx": result.get("path"), "cases_json": str(cases_path),
            "emitted_autoids": [c["autoid"] for c in cases], "not_sealed_autoids": missing,
            "verify": {"pass": verify.get("pass"), "fail": verify.get("fail"),
                       "failures": verify.get("failures")}}


__all__ = ["criterion_record", "emit", "expand_case", "prepare", "source_case_slice", "submit_case"]
